# Arrays multidimensionales

Anteriormente vimos como trabajar con arrays de una dimensión, ahora veamos como se trasladan esos conceptos cuando tienen 2 o más dimensiones.

## Índices 2D

Podemos imaginar un array 2D como una `tabla` con filas y columnas:

In [1]:
import numpy as np

arr_2d = np.array(([0,5,10], [15,20,25], [30,35,40]))

In [2]:
arr_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [3]:
arr_2d.shape

(3, 3)

In [4]:
arr_2d.ndim

2

Si tenemos dos dimensiones necesitamos dos índices, uno para las filas y otro para las columnas:

In [5]:
arr_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [9]:
# primera fila
arr_2d[2]

array([30, 35, 40])

In [14]:
# primera fila y primera columna
arr_2d[2,1] # = arr_2d[2][1]

35

In [13]:
# última fila y última columna
arr_2d[-1,-1]

40

In [11]:
# edición de la primera columna en la última fila
arr_2d[-1][0] = 99

In [12]:
arr_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

## Slicing 2D

Podemos utilizr el slicing doblando los indices de inicio y fin separándolos con una coma:

In [15]:
arr_2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [17]:
# subarray con todas las filas y columnas
arr_2d[:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [19]:
# subarray de las dos primeras filas
arr_2d[:2][:]

array([[ 0,  5, 10],
       [15, 20, 25]])

In [42]:
arr_2d

array([[  0,  99,  10],
       [ 15,  99,  25],
       [ 88, 200, 203]])

In [43]:
# subarray de la primera columna
arr_2d[:,:1]

array([[ 0],
       [15],
       [88]])

In [44]:
arr_2d[1:,:1] #[inicio: fin+1: step]

array([[15],
       [88]])

Mediante esta lógica podemos modificar los elementos masivamente:

In [45]:
arr_2d

array([[  0,  99,  10],
       [ 15,  99,  25],
       [ 88, 200, 203]])

In [36]:
# edición masiva de la segunda columna 
arr_2d[:,1:2] = 99 #[inicio: fin+1: step]

In [40]:
arr_2d

array([[  0,  99,  10],
       [ 15,  99,  25],
       [ 88, 200, 203]])

In [38]:
# edición masiva de la última fila
arr_2d[-1,:] = [88, 200, 203]

In [39]:
arr_2d

array([[  0,  99,  10],
       [ 15,  99,  25],
       [ 88, 200, 203]])

## Fancy index

Esta técnica se basa en pasarle una lista al array haciendo referencia a las filas donde queremos acceder.

In [46]:
# creamos un array 2d de ceros
arr_2d = np.zeros((5,10))

In [47]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
# modificación masiva de la primera, tercera y última fila
arr_2d[[0,2,-1]] = 5

In [49]:
arr_2d

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

Podemos consultar el array a voluntad, incluso repitiendo filas:

In [50]:
arr_2d[[0,1,1,1,0]]

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

## Bucles

Podemos recorrer las filas de un array con un bucle `for` como si de una lista se tratase:

In [51]:
arr_2d

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [52]:
for fila in arr_2d:
    print(fila)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Utilizando enumeradores podemos sacar el índice de cada posición de la fila y el de la columna y asignarle algo:

In [53]:
for i,fila in enumerate(arr_2d):
    for j,columna in enumerate(fila):
        arr_2d[i][j] = len(fila) * i + j

In [54]:
arr_2d

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

## Arrays 3D y más dimensiones

Hasta ahora hemos trabajado los arrays de 1 y 2 dimensiones, ¿será posible hacer lo mismo con 3 o más dimensiones?

El truco para manejar arrays de más dimensiones es anidar niveles de profundidad.

Vamos a recrear los 3 niveles de profundidad paso a paso para un array muy simple de 2x2x2:

In [ ]:
# primer nivel con 2 de ancho 
arr_1d = np.array(    [1, 2])

In [ ]:
arr_1d

In [ ]:
# segundo nivel con 2 de ancho y 2 de alto (2*2=4)
arr_2d = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

In [ ]:
arr_2d

In [ ]:
# tercer nivel con 2 de ancho, 2 de alto y 2 de profundidad (2*2*2=8)
arr_3d = np.array(
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ]
)

In [ ]:
arr_3d

Con esto tenemos 3 dimensiones pero podemos añadir más.

El concepto es difícil de imaginar, nosotros únicamente percibimos 3 dimensiones pero si lo entendemos como una ramificación dónde para cada elemento hay otra lista con varios elementos, entonces podemos hacernos una idea:

In [ ]:
# Cuarto nivel con 2 de ancho, 2 de alto, 2 de profundidad y 2 de... ¿espacio/tiempo? xD
arr_4d = np.array(
    [
        [
            [
                [1, 2],
                [3, 4]
            ],
            [
                [5, 6],
                [7, 8]
            ]
        ],
        [
            [
                [9, 10],
                [11, 12]
            ],
            [
                [13, 14],
                [15, 16]
            ]
        ]
    ]
)

In [ ]:
arr_4d

Podemos crear arrays multidimensionales con las funciones de pre-generación que ya vimos:

In [ ]:
# array 3d de ceros 2x2x2
arr_3d = np.zeros([2,2,2])

In [ ]:
arr_3d

In [ ]:
# array 4d de unos 2x2x2x2
arr_4d = np.ones([2,2,2,2])

In [ ]:
arr_4d

También podemos utilizar una función llamada `reshape` para reformar las dimensiones y sus tamaños:

In [ ]:
# reshape de un rango con 9 elementos a una matriz 3x3
arr_2d = np.arange(9)
arr_2d

In [ ]:
arr_2d.reshape(3,3)

Evidentemente hay que seguir un patrón lógico, el número de elementos tiene que coincidir con el tamaño de las dimensiones multiplicadas:

In [ ]:
# esto no funcionará: 9 != 3x3x3
arr_3d = np.arange(9).reshape(3,2)

In [ ]:
# esto sí que funcionará: 27 == 3x3x3
arr_3d = np.arange(27).reshape(3,3,3)

In [ ]:
arr_3d

In [ ]:
np.zeros([2, 2, 2, 2])