# Arrays transpuestos

Un array transpuesto es el reflejo de otro, de manera que las columnas se vuelven filas y las filas columna.

In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

El transpuesto del transpuesto es el arreglo original

In [4]:
arr.T.T

array([[1, 2, 3],
       [4, 5, 6]])

La función `swapaxes` sirve para intercambiar la posición de los dos ejes de un array, así que sirve para lo mismo:

In [5]:
# intercambiar filas por columnas
arr.swapaxes(0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

También podemos encontrar el array transpuesto de un array de 3 o más dimensiones:

In [6]:
arr_3d = np.arange(8)

In [7]:
arr_3d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
arr_3d = arr_3d.reshape(2, 2, 2)
arr_3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
new_arr_3d.shape

(2, 2, 2)

In [23]:
arr_3d.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

O intercambiar los ejes con `swapaxes`, por ejemplo la primera dimensión por la tercera, que en nuestro caso sería equivalente al array transpuesto:

In [25]:
arr_3d.swapaxes(0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

En cambio no sería equivalente intercambiar la primera por la segunda:

In [26]:
arr_3d.swapaxes(0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])