# Funciones universales

En esta lección vamos a ver algunas de las funciones universales. Se llaman así porque sirven para aplicar funciones matemáticas comunes en los elementos.


Podemos encontrar:

* Operaciones matemáticas
* Operaciones trigonométricas
* Operaciones comparativas
* Operaciones flotantes
* Operaciones de intercambio de bits

[En la documentación oficial](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs) encontraréis el listado completo con ejemplos de uso, vamos a practicar las más utilizadas.

## Matemáticas

In [1]:
import numpy as np

# arrays de prueba
arr_1 = np.arange(1,6)
arr_2 = np.array([-3,7,3,13,0])

In [2]:
arr_1

array([1, 2, 3, 4, 5])

In [3]:
arr_2

array([-3,  7,  3, 13,  0])

In [4]:
# suma
np.add(arr_1, arr_2)

array([-2,  9,  6, 17,  5])

In [5]:
# resta
np.subtract(arr_2, arr_1)

array([-4,  5,  0,  9, -5])

In [11]:
arr_1

array([1, 2, 3, 4, 5])

In [6]:
# raiz cuadrada
np.sqrt(arr_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [7]:
# potencia
np.power(arr_1, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [8]:
arr_1

array([1, 2, 3, 4, 5])

In [9]:
arr_2

array([-3,  7,  3, 13,  0])

In [10]:
# signo
np.sign(arr_2)

array([-1,  1,  1,  1,  0])

## Trigonométricas

In [12]:
arr_1

array([1, 2, 3, 4, 5])

In [15]:
np.pi

3.141592653589793

In [13]:
# seno
np.sin(arr_1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [16]:
# coseno
np.cos(arr_1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [17]:
# tangente
np.tan(arr_1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [18]:
# grados a radianes
np.deg2rad(arr_1)

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [19]:
# radianes a grados
np.rad2deg(arr_1)

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
       286.47889757])

## Comparativas

In [20]:
def convert_grad_2_radians(param1: int, param2: np.array, **kwards):
    """
    description of the function
    params:
    param1: int what is used for
    param2: int what is used for
    kwards: contains list of params to be used for the model
    outputs:
    
    """
    pass

In [21]:
arr_1, arr_2

(array([1, 2, 3, 4, 5]), array([-3,  7,  3, 13,  0]))

In [22]:
# máximo
np.maximum(arr_1, arr_2)

array([ 1,  7,  3, 13,  5])

In [23]:
# mínimo
np.minimum(arr_1, arr_2)

array([-3,  2,  3,  4,  0])

In [24]:
# igual que
np.equal(arr_1, arr_2)

array([False, False,  True, False, False])

In [26]:
arr_1, arr_2

(array([1, 2, 3, 4, 5]), array([-3,  7,  3, 13,  0]))

In [25]:
# mayor que
np.greater(arr_1, arr_2)

array([ True, False, False, False,  True])

## Flotantes

In [27]:
# tercer array de prueba
arr_3 = np.array([3.14, 2.57, -6.4, 0.47, 5.5])

In [28]:
# valor absoluto
np.fabs(arr_3)

array([3.14, 2.57, 6.4 , 0.47, 5.5 ])

In [29]:
# techo (redondeo entero al alza)
np.ceil(arr_3)

array([ 4.,  3., -6.,  1.,  6.])

In [30]:
# suelo (redondeo entero a la baja)
np.floor(arr_3)

array([ 3.,  2., -7.,  0.,  5.])