# Métodos internos

En esta lección vamos a repasar algunos métodos estadísticos y de ordenación que incluyen las instancias de la clase array. Para más información tenéis [la documentación oficial](https://numpy.org/doc/stable/reference/index.html).

## Métodos estadísticos

In [1]:
import numpy as np

# generamos un array de 2*3 con números aleatorios
arr = np.arange(1,7)

arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr_2d = arr.reshape(2,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# sumatorio
arr.sum(), arr_2d.sum()

(21, 21)

In [6]:
# media
arr.mean()

3.5

In [7]:
# desviación estándard
arr.std()

1.707825127659933

In [8]:
# varianza
arr.var()

2.9166666666666665

## Métodos de ordenación

In [9]:
import numpy as np

In [10]:
# generamos un nuevo array aleatorio
arr = np.random.randint(-10,10,[3,3])

arr

array([[-8,  4, -8],
       [ 5,  8,  5],
       [-1,  5, -1]])

In [14]:
# Ordenar elementos horizontalmente
arr.sort()

arr

array([[-8, -8,  4],
       [ 5,  5,  8],
       [-1, -1,  5]])

In [15]:
# Ordenar elementos verticalmente
arr.sort(0)

arr

array([[-8, -8,  4],
       [-1, -1,  5],
       [ 5,  5,  8]])

In [16]:
arr

array([[-8, -8,  4],
       [-1, -1,  5],
       [ 5,  5,  8]])