# Métodos internos

En esta lección vamos a repasar algunos métodos estadísticos y de ordenación que incluyen las instancias de la clase array. Para más información tenéis [la documentación oficial](https://numpy.org/doc/stable/reference/index.html).

## Métodos estadísticos

In [ ]:
import numpy as np

# generamos un array de 2*3 con números aleatorios
arr = np.arange(1,7)

arr

In [ ]:
arr.reshape(2,3)

In [ ]:
# sumatorio
arr.sum()

In [ ]:
# media
arr.mean()

In [ ]:
# desviación estándard
arr.std()

In [ ]:
# varianza
arr.var()

## Métodos de ordenación

In [2]:
import numpy as np

In [3]:
# generamos un nuevo array aleatorio
arr = np.random.randint(-10,10,[3,3])

arr

array([[-3, -2,  4],
       [ 7,  7, -4],
       [ 8,  2, -8]])

In [ ]:
# Ordenar elementos horizontalmente
arr.sort()

arr

In [4]:
# Ordenar elementos verticalmente
arr.sort(0)

arr

array([[-3, -2, -8],
       [ 7,  2, -4],
       [ 8,  7,  4]])

In [5]:
arr

array([[-3, -2, -8],
       [ 7,  2, -4],
       [ 8,  7,  4]])