# Ejercicio

1. Crear una lista de 4x3 elementos, con valores diferentes
1. Convertir esa lista a arreglo
1. Mostrar cómo acceder a la 3 fila de la lista
1. Mostrar cómo acceder a la 3 fila del arreglo
1. Mostrar cómo acceder a la 2 columna de la lista
1. Mostrar cómo acceder a la 2 columna del arreglo

In [4]:
import numpy as np

In [3]:
n, m = 4, 3

lista = []
for i in range(n):
    aux = []
    for j in range(m):
        aux.append(i*m + j)
    lista.append(aux)
    
lista

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]

In [5]:
arreglo = np.array(lista)
arreglo

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
# 3ra fila de la lista
lista[2]

[6, 7, 8]

In [17]:
# 3ra fila del array
arreglo[2]

array([6, 7, 8])

In [18]:
# 2da columna de la lista
columna = []
for fila in lista:
    columna.append(fila[1])
columna

[1, 4, 7, 10]

In [19]:
columna = [fila[1] for fila in lista]
columna

[1, 4, 7, 10]

In [21]:
lista_m = [lista[0][1], lista[1][1], lista[2][1], lista[3][1]]
lista_m

[1, 4, 7, 10]

In [24]:
arreglo

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
# 2da columna del array
arreglo[:,1]

array([ 1,  4,  7, 10])

In [25]:
arreglo[:,1:3]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [28]:
lista

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]

In [37]:
value = enumerate('lista')
list(value)

[(0, 'l'), (1, 'i'), (2, 's'), (3, 't'), (4, 'a')]

In [31]:
for idx, fila in enumerate(lista):
    for idxj, columna in enumerate(fila):
        print(lista[idx][idxj])

0
1
2
3
4
5
6
7
8
9
10
11
