# Manejo de arrays

## Índices

En la programación cuando trabajamos con colecciones de datos uno de los conceptos más importante es el `índice`.

In [1]:
import numpy as np

arr = np.arange(0, 50, 5)

In [2]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

El índice en los arrays funciona exactamente igual que en las listas, es simplemente un número que hace referencia a la posición que queremos consultar o modificar, empezando éste a contarse en 0:

In [3]:
# primera posición
arr[0]

0

In [4]:
# quinta posición
arr[4]

20

In [5]:
# última posición
arr[-1]  

45

In [6]:
# asignación de un valor
arr[-1] = 99  

In [7]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 99])

## Slicing

Igual con las listas, el slicing nos permite acceder y modificar un rango en base a dos índices, uno de inicio y otro de fin separados por dos puntos. Si dejamos los índices vacíos se toman por defecto el principio y el final:

In [8]:
# copia completa de principio a fin
arr[:]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 99])

In [9]:
# subarray de los 3 primers elementos
arr[:3]

array([ 0,  5, 10])

In [10]:
# modificar rango de forma masiva menos primero y último
arr[1:-1] = 50

In [11]:
arr

array([ 0, 50, 50, 50, 50, 50, 50, 50, 50, 99])

## Consideraciones importantes

Los arrays son objetos y por tanto se encuentran referenciados en la memoria.

A la hora de trabajar con subarrays todos los cambios que hagamos en ellos se verán reflejados en el array original:

In [12]:
# cremos un nuevo array
arr = np.arange(0, 30, 3)

In [13]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
# extraemos un subarray
sub_arr = arr[0:4]

In [15]:
sub_arr

array([0, 3, 6, 9])

In [17]:
# lo modificamos
sub_arr[:] = 99
sub_arr

array([99, 99, 99, 99])

In [18]:
# veamos el array original...
arr

array([99, 99, 99, 99, 12, 15, 18, 21, 24, 27])

## Copia de arrays

Mediante el método `copy` podemos crear una copia, de manera que tengamos dos objetos y los cambios del subarray ya no afecten al original:

In [24]:
# cremos un nuevo array
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [20]:
# extraemos el subarray pero de una copia
sub_arr = arr[0:4].copy()
sub_arr

array([0, 3, 6, 9])

In [21]:
# lo modificamos
sub_arr[:] = 99

In [22]:
sub_arr

array([99, 99, 99, 99])

In [23]:
# veamos el array original...
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])